title: "Yu-Leung Ng"
author: "Yu-Leung Ng"
description: "Assistant Professor, Department of Interactive Media, HKBU"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "publications.md", title: "Selected Publications"}
  - {file: "research.md", title: "Research"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: <ins>Faculty Webpage</ins>, url: https://imd.hkbu.edu.hk/faculty-member/Dr-NG-Yu-Leung.html}
 
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
